### ISSUE TITLE
Disconnection and reconnection problem

### ISSUE THREAD

**Issue by jingyinzhou** [SpryRocks/capacitor-socket-connection-plugin#23]
断线之后调用open方法，会提示我open方法只能调用一次，我应该如何重连？

我看了源码，关键在这里：this.checkStateOrThrow('initial', `You can call "open" method only once`);
onClose方法已经触发，内部的state应该变为closed状态， 然后我再调用open方法，就会输出：You can call "open" method only once

**Comment by maximzhemerenko** [comment]
Hello @jingyinzhou, to re-connect the socket you should create the new one and open it. I will update the documentation to clarify this moment, thank you.

**Comment by jingyinzhou** [comment]
thank you.
