### ISSUE TITLE
about connect

### ISSUE THREAD

**Issue by jingyinzhou** [SpryRocks/capacitor-socket-connection-plugin#24]
Sending plugin error: {"save":false,"callbackId":"68532909","pluginId":"CapacitorSocketConnectionPlugin","methodName":"sendData","success":false,"error":{"message":"Cannot find socket with provided uuid","code":"{\"message\":\"Cannot find socket with provided uuid\"}"}}

Line 163 - Msg: Uncaught (in promise) Error: Cannot find socket with provided uuid

![QQ截图20240408145255](https://github.com/SpryRocks/capacitor-socket-connection-plugin/assets/42663704/3d9c52a1-6264-4a79-ad78-26d73388abce)

**Comment by maximzhemerenko** [comment]
Hello @jingyinzhou, how can I reproduce this error? Maybe you can provide me some code that I can use and test on my side?

**Comment by jingyinzhou** [comment]
TCP重连的时候，就会出现这个问题。很奇怪。TCP重连需要重连很多次才能连上，而且连上之后发送数据，很大概率就会出现这个问题，非常奇怪，出现这个错误的时候，TCP连接并没有断开。

多谢您解答我的问题！

**Comment by maximzhemerenko** [comment]
I cannot reproduce this error in my app
