### ISSUE TITLE
Note for future users

### ISSUE THREAD

**Issue by redalpha01** [SpryRocks/capacitor-socket-connection-plugin#26]
1. Socket.state is sadly private
2. You need androidToolsBuildGradleVersion in your android/gradle.properties

**Comment by maximzhemerenko** [comment]
Hello @redalpha01, thank you for your feedback, I will review it soon

**Comment by maximzhemerenko** [comment]
1. Made state getter public

**Comment by maximzhemerenko** [comment]
2. Fixed and tested on fresh Ionic project
